### ISSUE TITLE
Voxel shader stretches the texture

### ISSUE THREAD

**Issue by michbr** [autarch-design-team/OpenCircuit#8]
Steps to reproduce:
1. Create a horizontal surface using the rectangle brush
2. Texture stretching appears
![stretchingdefect](https://cloud.githubusercontent.com/assets/5962914/10300651/acf70782-6bb6-11e5-80cf-d791ae83038c.PNG)

**Comment by semimono** [comment]
This is SO old (and I haven't been noticing it at all) that I'm going to close it.  We can reopen it if we find a good way to reproduce it, but I haven't seen it in months.
